name: Project1 Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - run: |
          whoami
          nvm use 22.15.1
          node -v
          npm i
          npm run build